[package]
name = "rs-pderiv-test3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bitvec = "1"
# bit-vec = "0.6"
# intmap = "2.0.0"
rs-pdriv = "0.1.0"